import { ProductDetailDTO } from "@/modules/catalog/contracts";

const categorias = {
  rituales: {
    id: "cat_rituales",
    slug: "rituales-nocturnos",
    nombre: "Rituales nocturnos",
    descripcion: "Aromas cálidos para cerrar el día.",
  },
  ligeros: {
    id: "cat_ligeros",
    slug: "dias-ligeros",
    nombre: "Dias ligeros",
    descripcion: "Fragancias limpias para espacios luminosos.",
  },
  especiales: {
    id: "cat_especiales",
    slug: "especiales",
    nombre: "Especiales",
    descripcion: "Colecciones de regalo y temporada.",
  },
};

export const fallbackProducts: ProductDetailDTO[] = [
  {
    id: "prod_ambar_canela",
    slug: "ambar-canela",
    nombre: "Ambar Canela",
    descripcion:
      "Vela artesanal con notas de ambar, canela suave y vainilla tostada.",
    precioReferencia: 68000,
    imagenes: ["/images/products/ambar-canela.svg"],
    activo: true,
    createdAt: "2026-03-01T10:00:00.000Z",
    updatedAt: "2026-03-15T10:00:00.000Z",
    categoryId: categorias.rituales.id,
    categoria: categorias.rituales,
    variantes: [
      {
        id: "var_ambar_220",
        productId: "prod_ambar_canela",
        nombreVariante: "220g",
        sku: "FOG-AMB-220",
        stockVirtual: 35,
        precio: 68000,
      },
      {
        id: "var_ambar_350",
        productId: "prod_ambar_canela",
        nombreVariante: "350g",
        sku: "FOG-AMB-350",
        stockVirtual: 18,
        precio: 90000,
      },
    ],
  },
  {
    id: "prod_lavanda_algodon",
    slug: "lavanda-algodon",
    nombre: "Lavanda Algodon",
    descripcion: "Lavanda limpia y algodón fresco para espacios tranquilos.",
    precioReferencia: 62000,
    imagenes: ["/images/products/lavanda-algodon.svg"],
    activo: true,
    createdAt: "2026-04-05T10:00:00.000Z",
    updatedAt: "2026-04-07T10:00:00.000Z",
    categoryId: categorias.ligeros.id,
    categoria: categorias.ligeros,
    variantes: [
      {
        id: "var_lavanda_220",
        productId: "prod_lavanda_algodon",
        nombreVariante: "220g",
        sku: "FOG-LAV-220",
        stockVirtual: 42,
        precio: 62000,
      },
    ],
  },
  {
    id: "prod_coco_sandalo",
    slug: "coco-sandalo",
    nombre: "Coco Sandalo",
    descripcion: "Aroma envolvente de coco cremoso y fondo de sándalo.",
    precioReferencia: 70000,
    imagenes: ["/images/products/coco-sandalo.svg"],
    activo: true,
    createdAt: "2026-02-20T10:00:00.000Z",
    updatedAt: "2026-03-01T10:00:00.000Z",
    categoryId: categorias.rituales.id,
    categoria: categorias.rituales,
    variantes: [
      {
        id: "var_coco_220",
        productId: "prod_coco_sandalo",
        nombreVariante: "220g",
        sku: "FOG-COC-220",
        stockVirtual: 24,
        precio: 70000,
      },
      {
        id: "var_coco_350",
        productId: "prod_coco_sandalo",
        nombreVariante: "350g",
        sku: "FOG-COC-350",
        stockVirtual: 12,
        precio: 95000,
      },
    ],
  },
  {
    id: "prod_te_higo",
    slug: "te-blanco-higo",
    nombre: "Te Blanco Higo",
    descripcion:
      "Salida frutal sutil con base herbal para tardes de descanso en casa.",
    precioReferencia: 64000,
    imagenes: ["/images/products/te-blanco-higo.svg"],
    activo: true,
    createdAt: "2026-04-08T10:00:00.000Z",
    updatedAt: "2026-04-08T10:00:00.000Z",
    categoryId: categorias.ligeros.id,
    categoria: categorias.ligeros,
    variantes: [
      {
        id: "var_te_higo_220",
        productId: "prod_te_higo",
        nombreVariante: "220g",
        sku: "FOG-TEB-220",
        stockVirtual: 28,
        precio: 64000,
      },
    ],
  },
  {
    id: "prod_pack_duo",
    slug: "pack-regalo-duo",
    nombre: "Pack Regalo Duo",
    descripcion: "Set de dos velas artesanales en empaque premium para regalo.",
    precioReferencia: 125000,
    imagenes: ["/images/products/pack-regalo-duo.svg"],
    activo: true,
    createdAt: "2026-03-25T10:00:00.000Z",
    updatedAt: "2026-04-01T10:00:00.000Z",
    categoryId: categorias.especiales.id,
    categoria: categorias.especiales,
    variantes: [
      {
        id: "var_pack_duo",
        productId: "prod_pack_duo",
        nombreVariante: "Duo 220g",
        sku: "FOG-PKD-220",
        stockVirtual: 11,
        precio: 125000,
      },
    ],
  },
];
