type ShippingRateCategory = "local" | "regional" | "nacional" | "zonal" | "otros" | "especial";

// Promedios unitarios COP derivados del escenario "Caja 4 grandes" / 4 unidades.
const averageShippingCostPerUnitByCategory: Record<ShippingRateCategory, number> = {
  local: 4158,
  regional: 5493,
  nacional: 7911,
  zonal: 9036,
  otros: 11988,
  especial: 15291,
};

const destinations: Array<{
  destino: string;
  departamento: string;
  category: ShippingRateCategory;
}> = [
  { destino: "Bogota D.C.", departamento: "Bogota D.C.", category: "local" },
  { destino: "Soacha", departamento: "Cundinamarca", category: "regional" },
  { destino: "Chia", departamento: "Cundinamarca", category: "regional" },
  { destino: "Cajica", departamento: "Cundinamarca", category: "regional" },
  { destino: "Zipaquira", departamento: "Cundinamarca", category: "regional" },
  { destino: "Cota", departamento: "Cundinamarca", category: "regional" },
  { destino: "Funza", departamento: "Cundinamarca", category: "regional" },
  { destino: "Mosquera", departamento: "Cundinamarca", category: "regional" },
  { destino: "Madrid", departamento: "Cundinamarca", category: "regional" },
  { destino: "Facatativa", departamento: "Cundinamarca", category: "regional" },
  { destino: "Tocancipa", departamento: "Cundinamarca", category: "regional" },
  { destino: "Sibate", departamento: "Cundinamarca", category: "regional" },
  { destino: "Fusagasuga", departamento: "Cundinamarca", category: "regional" },
  { destino: "Girardot", departamento: "Cundinamarca", category: "regional" },
  { destino: "Tunja", departamento: "Boyaca", category: "regional" },
  { destino: "Duitama", departamento: "Boyaca", category: "regional" },
  { destino: "Sogamoso", departamento: "Boyaca", category: "regional" },
  { destino: "Chiquinquira", departamento: "Boyaca", category: "regional" },
  { destino: "Medellin", departamento: "Antioquia", category: "nacional" },
  { destino: "Bello", departamento: "Antioquia", category: "nacional" },
  { destino: "Itagui", departamento: "Antioquia", category: "nacional" },
  { destino: "Envigado", departamento: "Antioquia", category: "nacional" },
  { destino: "Sabaneta", departamento: "Antioquia", category: "nacional" },
  { destino: "Rionegro", departamento: "Antioquia", category: "nacional" },
  { destino: "Apartado", departamento: "Antioquia", category: "otros" },
  { destino: "Turbo", departamento: "Antioquia", category: "otros" },
  { destino: "Cali", departamento: "Valle del Cauca", category: "nacional" },
  { destino: "Palmira", departamento: "Valle del Cauca", category: "nacional" },
  { destino: "Yumbo", departamento: "Valle del Cauca", category: "nacional" },
  { destino: "Jamundi", departamento: "Valle del Cauca", category: "nacional" },
  { destino: "Buenaventura", departamento: "Valle del Cauca", category: "otros" },
  { destino: "Tulua", departamento: "Valle del Cauca", category: "nacional" },
  { destino: "Buga", departamento: "Valle del Cauca", category: "nacional" },
  { destino: "Cartago", departamento: "Valle del Cauca", category: "nacional" },
  { destino: "Barranquilla", departamento: "Atlantico", category: "nacional" },
  { destino: "Soledad", departamento: "Atlantico", category: "nacional" },
  { destino: "Malambo", departamento: "Atlantico", category: "nacional" },
  { destino: "Puerto Colombia", departamento: "Atlantico", category: "nacional" },
  { destino: "Cartagena", departamento: "Bolivar", category: "nacional" },
  { destino: "Turbaco", departamento: "Bolivar", category: "nacional" },
  { destino: "Arjona", departamento: "Bolivar", category: "zonal" },
  { destino: "Magangue", departamento: "Bolivar", category: "zonal" },
  { destino: "Santa Marta", departamento: "Magdalena", category: "nacional" },
  { destino: "Cienaga", departamento: "Magdalena", category: "nacional" },
  { destino: "Zona Bananera", departamento: "Magdalena", category: "zonal" },
  { destino: "Bucaramanga", departamento: "Santander", category: "nacional" },
  { destino: "Floridablanca", departamento: "Santander", category: "nacional" },
  { destino: "Giron", departamento: "Santander", category: "nacional" },
  { destino: "Piedecuesta", departamento: "Santander", category: "nacional" },
  { destino: "Barrancabermeja", departamento: "Santander", category: "nacional" },
  { destino: "Cucuta", departamento: "Norte de Santander", category: "nacional" },
  { destino: "Villa del Rosario", departamento: "Norte de Santander", category: "nacional" },
  { destino: "Los Patios", departamento: "Norte de Santander", category: "nacional" },
  { destino: "Ocana", departamento: "Norte de Santander", category: "zonal" },
  { destino: "Tibu", departamento: "Norte de Santander", category: "especial" },
  { destino: "Pereira", departamento: "Risaralda", category: "nacional" },
  { destino: "Dosquebradas", departamento: "Risaralda", category: "nacional" },
  { destino: "Santa Rosa de Cabal", departamento: "Risaralda", category: "nacional" },
  { destino: "Manizales", departamento: "Caldas", category: "nacional" },
  { destino: "Villamaria", departamento: "Caldas", category: "nacional" },
  { destino: "La Dorada", departamento: "Caldas", category: "nacional" },
  { destino: "Armenia", departamento: "Quindio", category: "nacional" },
  { destino: "Calarca", departamento: "Quindio", category: "nacional" },
  { destino: "Ibague", departamento: "Tolima", category: "nacional" },
  { destino: "Espinal", departamento: "Tolima", category: "regional" },
  { destino: "Neiva", departamento: "Huila", category: "nacional" },
  { destino: "Pitalito", departamento: "Huila", category: "zonal" },
  { destino: "Villavicencio", departamento: "Meta", category: "regional" },
  { destino: "Acacias", departamento: "Meta", category: "regional" },
  { destino: "Granada", departamento: "Meta", category: "zonal" },
  { destino: "Puerto Gaitan", departamento: "Meta", category: "otros" },
  { destino: "Yopal", departamento: "Casanare", category: "nacional" },
  { destino: "Aguazul", departamento: "Casanare", category: "zonal" },
  { destino: "Monteria", departamento: "Cordoba", category: "nacional" },
  { destino: "Cerete", departamento: "Cordoba", category: "nacional" },
  { destino: "Lorica", departamento: "Cordoba", category: "zonal" },
  { destino: "Sincelejo", departamento: "Sucre", category: "nacional" },
  { destino: "Corozal", departamento: "Sucre", category: "nacional" },
  { destino: "Valledupar", departamento: "Cesar", category: "nacional" },
  { destino: "Aguachica", departamento: "Cesar", category: "zonal" },
  { destino: "Riohacha", departamento: "La Guajira", category: "nacional" },
  { destino: "Maicao", departamento: "La Guajira", category: "nacional" },
  { destino: "Uribia", departamento: "La Guajira", category: "especial" },
  { destino: "Manaure", departamento: "La Guajira", category: "especial" },
  { destino: "Pasto", departamento: "Narino", category: "nacional" },
  { destino: "Ipiales", departamento: "Narino", category: "nacional" },
  { destino: "Tumaco", departamento: "Narino", category: "especial" },
  { destino: "Tuquerres", departamento: "Narino", category: "zonal" },
  { destino: "Popayan", departamento: "Cauca", category: "nacional" },
  { destino: "Santander de Quilichao", departamento: "Cauca", category: "zonal" },
  { destino: "Quibdo", departamento: "Choco", category: "especial" },
  { destino: "Istmina", departamento: "Choco", category: "especial" },
  { destino: "Acandi", departamento: "Choco", category: "especial" },
  { destino: "Unguia", departamento: "Choco", category: "especial" },
  { destino: "Arauca", departamento: "Arauca", category: "nacional" },
  { destino: "Arauquita", departamento: "Arauca", category: "zonal" },
  { destino: "Saravena", departamento: "Arauca", category: "zonal" },
  { destino: "Mocoa", departamento: "Putumayo", category: "zonal" },
  { destino: "Puerto Asis", departamento: "Putumayo", category: "zonal" },
  { destino: "Puerto Leguizamo", departamento: "Putumayo", category: "especial" },
  { destino: "Valle del Guamuez", departamento: "Putumayo", category: "especial" },
  { destino: "San Miguel", departamento: "Putumayo", category: "especial" },
  { destino: "Florencia", departamento: "Caqueta", category: "nacional" },
  { destino: "San Vicente del Caguan", departamento: "Caqueta", category: "otros" },
  { destino: "Leticia", departamento: "Amazonas", category: "especial" },
  { destino: "Puerto Narino", departamento: "Amazonas", category: "especial" },
  { destino: "Inirida", departamento: "Guainia", category: "especial" },
  { destino: "Barrancominas", departamento: "Guainia", category: "especial" },
  { destino: "Mitu", departamento: "Vaupes", category: "especial" },
  { destino: "Taraira", departamento: "Vaupes", category: "especial" },
  { destino: "Puerto Carreno", departamento: "Vichada", category: "especial" },
  { destino: "La Primavera", departamento: "Vichada", category: "especial" },
  { destino: "San Andres", departamento: "San Andres y Providencia", category: "especial" },
  { destino: "Providencia", departamento: "San Andres y Providencia", category: "especial" },
];

function toDestinationSlug(destino: string, departamento: string) {
  return `${destino}-${departamento}`
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export const shippingDestinationRates = destinations.map((destination) => ({
  destino: destination.destino,
  departamento: destination.departamento,
  destinoSlug: toDestinationSlug(destination.destino, destination.departamento),
  promedioEnvioUnitario: averageShippingCostPerUnitByCategory[destination.category],
  activo: true,
}));
